Document: ic35link
Title: Debian ic35link Manual
Author: <insert document author here>
Abstract: This manual describes what ic35link is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ic35link/ic35link.sgml.gz

Format: postscript
Files: /usr/share/doc/ic35link/ic35link.ps.gz

Format: text
Files: /usr/share/doc/ic35link/ic35link.text.gz

Format: HTML
Index: /usr/share/doc/ic35link/html/index.html
Files: /usr/share/doc/ic35link/html/*.html
